name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # - name: Terraform Init
    #   working-directory: ./terraform/bootstrap
    #   run: terraform init

    # - name: Terraform Apply
    #   working-directory: ./terraform/bootstrap
    #   run: terraform apply -auto-approve
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Build and Push Backend
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: ./backend
    #     push: true
    #     tags: |
    #       ${{ secrets.DOCKER_USERNAME }}/myproject-backend:${{ github.sha }}
    #       ${{ secrets.DOCKER_USERNAME }}/myproject-backend:latest
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max

    # - name: Build and Push Frontend
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: ./frontend
    #     push: true
    #     tags: |
    #       ${{ secrets.DOCKER_USERNAME }}/myproject-frontend:${{ github.sha }}
    #       ${{ secrets.DOCKER_USERNAME }}/myproject-frontend:latest
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max

    - name: Terraform Init
      working-directory: ./terraform/aws
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform/aws
      run: terraform destroy -auto-approve -lock=false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
        TF_VAR_image_tag: ${{ github.sha }}

 
